server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: bookstore
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yaml